version: '3'
services:
  db:
    image: mysql:5
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./tmp/db:/var/lib/mysql
  app:
    build: .
    volumes:
      - .:/template
      - node_modules:/template/node_modules
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - db
volumes:
  node_modules:
