blank_issues_enabled: true
contact_links:
  - name: Issue
    about: Issue template
    url: https://github.com/funasshi/dokugaku-no-mori/issues/new?template=issue.md&projects=funasshi/projects/2&labels=enhancement
